# The URL the site will be built for
base_url = "https://williamhatch.github.io/william_blog"

# Whether to automatically compile all Sass files in the sass directory
compile_sass = true

# Whether to build a search index to be used later on by a JavaScript library
build_search_index = true

taxonomies = [
    { name = "tags" }
]

# theme = "zolarwind"

[markdown]
# Whether to do syntax highlighting
# Theme can be customised by setting the `highlight_theme` variable to a theme supported by Zola
highlight_code = true

[extra]
title = "William's Blog"
path_language_resources = "i18n/"

[[extra.menu_pages]]
title = "Blog"
url = "blog"

[[extra.social_links]]
name = "github"
url = "https://github.com/williamhatch"
icon = "fab fa-github"

[[extra.social_links]]
name = "linkedin"
url = "https://www.linkedin.com/in/yong-chen-2017/"
icon = "fab fa-linkedin"

[[extra.social_links]]
name = "dev"
url = "https://dev.to/williamhatch"
icon = "fab fa-dev"

[[extra.social_links]]
name = "medium"
url = "https://medium.com/@trees.william"
icon = "fab fa-medium"

[[extra.skills]]
name = "Rails"
description = "Rapidly developing robust web applications with the Ruby on Rails framework, focusing on convention over configuration."
tag = "Rails"

[[extra.skills]]
name = "Python"
description = "Leveraging Python for data analysis, machine learning, and building powerful backend services and automation scripts."
tag = "Python"

[[extra.skills]]
name = "Java"
description = "Engineering enterprise-grade, high-performance applications and services with a focus on stability and scalability."
tag = "Java"

[[extra.skills]]
name = "Go"
description = "Building simple, reliable, and efficient software, especially for concurrent systems and microservices architectures."
tag = "Go"

[[extra.skills]]
name = "Rust"
description = "Writing memory-safe and performant systems-level software, ensuring reliability for critical applications."
tag = "Rust"

[[extra.skills]]
name = "Vue.js"
description = "Crafting interactive and modern user interfaces with the progressively adaptable Vue.js framework."
tag = "Vue"

[[extra.skills]]
name = "React"
description = "Developing dynamic and component-based user interfaces for complex single-page applications."
tag = "React"

[[extra.skills]]
name = "Architecture"
description = "Designing scalable, resilient, and maintainable software systems, from monoliths to microservices."
tag = "Architecture"

[[extra.skills]]
name = "DevOps"
description = "Automating and optimizing software delivery pipelines, focusing on CI/CD, infrastructure as code, and observability."
tag = "DevOps"

[[extra.skills]]
name = "Data"
description = "Working with data pipelines, databases, and analytics to extract insights and drive business value."
tag = "Data"

[[extra.skills]]
name = "AI"
description = "Integrating machine learning models and AI-driven features into products to create intelligent solutions."
tag = "AI"
