name: GitHub Pages

on:
  push:
    branches:
      - main # or master

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write # Allow write permissions to GITHUB_TOKEN for deployment
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: true

      - name: Build and Deploy
        uses: shalzz/zola-deploy-action@v0.20.0
        env:
          # The branch the action should deploy to.
          PAGES_BRANCH: gh-pages
          # The token the action should use to push the built site to the gh-pages branch.
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Deploy
        # Only deploy when pushing to main
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        uses: peaceiris/actions-gh-pages@v3
        with:
          # GITHUB_TOKEN is a secret automatically provided by GitHub
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public 